from fastapi import APIRouter, UploadFile, File, HTTPException
from fastapi.responses import FileResponse
from pathlib import Path
import shutil
import uuid
import os

from app.core.redis_client import redis_client
from app.models.redis_keys import (
    user_slides_key,
    slide_key,
)

router = APIRouter(prefix="/files", tags=["Files"])

# Base directories
BASE_DIR = Path(__file__).resolve().parent.parent.parent
STORAGE_DIR = BASE_DIR / "storage"
UPLOAD_DIR = STORAGE_DIR / "slides"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------
# 1) UPLOAD WHOLE-SLIDE IMAGE (.svs)
# ---------------------------------------------------------------------
@router.post("/upload_wsi")
async def upload_wsi(user_id: str, file: UploadFile = File(...)):
    filename = file.filename.lower()

    if not filename.endswith(".svs"):
        raise HTTPException(400, "Only .svs files allowed")

    # Read file size
    file.file.seek(0, os.SEEK_END)
    size = file.file.tell()
    file.file.seek(0)

    if size == 0:
        raise HTTPException(400, "Uploaded file is empty")

    # Generate slide ID and store
    slide_id = str(uuid.uuid4())
    save_path = UPLOAD_DIR / f"{slide_id}.svs"

    with save_path.open("wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    # Store metadata in Redis
    await redis_client.sadd(user_slides_key(user_id), slide_id)
    await redis_client.hset(
        slide_key(slide_id),
        mapping={
            "slide_id": slide_id,
            "user_id": user_id,
            "slide_path": str(save_path),
            "size_bytes": size,
        }
    )

    return {
        "slide_id": slide_id,
        "slide_path": str(save_path),
        "size_bytes": size,
        "user_id": user_id,
    }


# ---------------------------------------------------------------------
# 2) LIST USER SLIDES
# ---------------------------------------------------------------------
@router.get("/user/{user_id}/slides")
async def list_slides(user_id: str):
    slide_ids = await redis_client.smembers(user_slides_key(user_id))
    slides = []

    for sid in slide_ids:
        meta = await redis_client.hgetall(slide_key(sid))
        if meta:
            slides.append(meta)

    return slides


# ---------------------------------------------------------------------
# 3) UNIVERSAL DOWNLOAD ENDPOINT — for job outputs & stored files
# ---------------------------------------------------------------------
@router.get("/download")
async def download_file(path: str):
    """
    Download files generated by jobs.
    All job outputs live under: backend/tmp/<filename>
    """

    clean = path.strip('"').strip("'")
    p = Path(clean)

    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    TMP_DIR = BASE_DIR / "tmp"
    SLIDES_DIR = BASE_DIR / "storage" / "slides"

    print("\n===== DOWNLOAD DEBUG =====")
    print("input path:", clean)
    print("BASE_DIR:", BASE_DIR)
    print("TMP_DIR:", TMP_DIR)

    # ---------- Resolve path ----------
    if clean.startswith("tmp/"):
        full = TMP_DIR / p.name
    elif "/tmp/" in clean:
        full = TMP_DIR / p.name
    elif "storage/slides" in clean:
        full = SLIDES_DIR / p.name
    else:
        full = TMP_DIR / p.name

    print("Resolved:", full)
    print("==========================\n")

    if not full.exists():
        raise HTTPException(404, f"File not found: {full}")

    return FileResponse(
        full,
        filename=full.name,
        media_type="application/octet-stream",
    )
